### ISSUE TITLE
Multiple monitor layout does not return after closing game

### ISSUE THREAD

**Issue by peanutlasko** [Nonary/ResolutionAutomation#20]
Issue: When quitting a game using Sunshine, the monitor layout doesn't return back to where it was prior.

Steps to reproduce:

Setup two monitors in Windows. I have a 3440x1440 (monitor1) resolution screen and a 1920x1080 (monitor2). Their orientation is as follows:

monitor1 > monitor2

Launch a game in Sunshine. Resolution of monitor1 correctly changes to 2560x1440. After qutting game, monitor1 changes back to 3440x1440, however the orentation is now:

monitor1
monitor2 

(stacked on top of each other)

**Comment by Nonary** [comment]
Multiple monitor layouts are unsupported because of the oddities with the windows API when using resolution changes targeted at the primary screen. As a workaround you can use the monitor swapper script to temporarily disable the other monitor while streaming.

https://github.com/Nonary/MonitorSwapAutomation

**Comment by peanutlasko** [comment]
This works. Thanks!
