### ISSUE TITLE
Script don't launch

### ISSUE THREAD

**Issue by Musyanon** [Nonary/ResolutionAutomation#25]
Hello,

I installed the script, but it doesn't work.

The script installed well, the execution command is well in the Sunshine configuration.

So I took the command "powershell.exe -executionpolicy bypass -WindowStyle Hidden -file `"MyPath\ResolutionMatcher-Functions.ps1" to try it manually in a terminal and it works! But another strange thing the command works only after a Windows logon, it doesn't work if I try again without first logging off.

Hoping you can help me.

**Comment by Nonary** [comment]
Sunshine can't execute commands without an active user session, if you're using something like Microsoft Remote Desktop it will break Sunshine until you sign back into the computer. The latest nightly version of Sunshine helps with this by allowing you to sign into Desktop if the scripts fail. Otherwise, you need to add a No Prep application, like mentioned in the scripts caveat section before you installed it.

**Comment by Nonary** [comment]
Closing out as this cannot be fixed due to limitations of windows API/
