### ISSUE TITLE
Screen reverts to intial resolution when using full screen apps/games

### ISSUE THREAD

**Issue by cobra872** [Nonary/ResolutionAutomation#31]
I am using Sunshine with a bunch of games set up correctly. However, some games launch Full Screen and it causes the desktop resolution to revert to the intial resolution. Is there any fix for this?

I suppose I could launch some of the games in a borderless window but I have problems doing that with certain games.

**Comment by Nonary** [comment]
The moment you tell a game to run full screen, it will no longer inherit any of the resolution settings from the desktop.

Which means the script can only work if you use Borderless Windowed Mode.

This is not a problem for the vast majority of modern games, because there technically isn't even a true full screen mode anymore. In fact, most modern games, when selecting full screen are still running in borderless windowed, due to a new Windows Direct X API feature called SwapChain.

SwapChain allows games to run in windowed mode, with no negatives from the past and will be just as performant as full screen.

However, you can only get this feature on modern games for the most part.

**HOWEVER** if you do have a Windows 11 computer, you can enable the "Optimizations for Windowed Games" feature, which essentially forces the SwapChain even on older games, effectively allowing you to run just about 95% of all games in borderless windowed without issues. This is **exclusive** to Windows 11 and only available to 22H2 and higher builds.

Please let me know if you have any further questions about this.

**Comment by cobra872** [comment]
> The moment you tell a game to run full screen, it will no longer inherit any of the resolution settings from the desktop.
> 
> Which means the script can only work if you use Borderless Windowed Mode.
> 
> This is not a problem for the vast majority of modern games, because there technically isn't even a true full screen mode anymore. In fact, most modern games, when selecting full screen are still running in borderless windowed, due to a new Windows Direct X API feature called SwapChain.
> 
> SwapChain allows games to run in windowed mode, with no negatives from the past and will be just as performant as full screen.
> 
> However, you can only get this feature on modern games for the most part.
> 
> **HOWEVER** if you do have a Windows 11 computer, you can enable the "Optimizations for Windowed Games" feature, which essentially forces the SwapChain even on older games, effectively allowing you to run just about 95% of all games in borderless windowed without issues. This is **exclusive** to Windows 11 and only available to 22H2 and higher builds.
> 
> Please let me know if you have any further questions about this.

Ok thanks for the info! It’s only a minor inconvenience so I wanted to see if there was another workaround.
