### ISSUE TITLE
some operational issues

### ISSUE THREAD

**Issue by XPRAMT** [Nonary/ResolutionAutomation#41]
When the client connects, I close the primary monitor, open the virtual monitor, and then adjust the resolution of the virtual monitor. When the client disconnects, the virtual monitor is closed, and the primary monitor is opened. Therefore, the restoration of the resolution is not important.

The current issue is that after the client disconnects, the virtual monitor closes, resulting in an incorrect restoration of the resolution on my primary monitor.

**Comment by Nonary** [comment]
You can use my monitor swap script to change the monitor, as long as you install it before the resolution script it will only change the resolution on the virtual screen.

https://github.com/Nonary/MonitorSwapAutomation/releases/tag/1.0.5

The reason why this is happening for you is because you're manually doing it, instead of using the script that automates the swap for you when you start and end the stream.

**Comment by Nonary** [comment]
No response, closing out
