### ISSUE TITLE
start Sunshine error

### ISSUE THREAD

**Issue by MrYaoShao** [Nonary/ResolutionAutomation#55]
[global_prep_cmd] -- [[{"do":"powershell.exe -executionpolicy bypass -WindowStyle Hidden -file \"D:\\Tool\\ResolutionMatcher\\ResolutionMatcher.ps1\"","elevated":"false","undo":"powershell.exe -executionpolicy bypass -WindowStyle Hidden -file \"D:\\Tool\\ResolutionMatcher\\ResolutionMatcher-Functions.ps1\" True"}]]
[resolutions] -- [[
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080
]]
[gamepad] -- [x360]
[amd_usage] -- [lowlatency]
[channels] -- [3]
terminate called after throwing an instance of 'boost::wrapexcept<boost::property_tree::json_parser::json_parser_error>'
  what():  <unspecified file>(1): invalid code sequence

**Comment by Nonary** [comment]
upload your sunshine.conf and apps.json files please

**Comment by Nonary** [comment]
No response from user

**Comment by antonmorch** [comment]
I know this thread is closed, but I encountered the same error, so I thought it nice to share my solution. 
I had the script installed under Documents folder and the file path therefor includes my windows account name. The idiot I am, included a special character in my user account name, which it seems the script don't know how to parse properly. 
When I installed the script under C: it all worked flawlessly, because it didn't have to handle my "ø" in the account name.
