### ISSUE TITLE
Choosing which display to change

### ISSUE THREAD

**Issue by Metaluca13** [Nonary/ResolutionAutomation#63]
I have a SUW monitor as my main display and just got a dummy HDMI dummy plug for sunshine/moonlight.
When I connect through moonlight to sunshine, the correct screen is streamed (I wrote the correct output name in config-> audio/video) however the resolutionAutomation is changed on my main display.

Is there a way to tell it to work on the same display that is streamed to Moonlight?

**Comment by Nonary** [comment]
Due to various issues with Sunshine in terms of streaming a specific display (it intermittently breaks when windows changes the display names), I do not recommend using it. Instead, use this script in conjunction with the resolution swap, just make sure its installed first, that way the swap happens before the resolution change

https://github.com/Nonary/MonitorSwapAutomation
