### ISSUE TITLE
Resolution is set to 0

### ISSUE THREAD

**Issue by jeff-os** [Nonary/ResolutionAutomation#7]
Nevermind.

**Comment by jeff-os** [comment]
The scripts will error out unless you set your execution policy to unrestricted at the system level, which is unsafe, but even when you do it, it still doesn't work because of hardcoded paths.

This seems like it would be trivial to implemet on a python  or C# app and would be safer.  Just parse the log file, use the win32api library which allows you to set resolutions, build a function around it to pass parameters.  You're done.  Am I missing something? I don't understand why you would choose to implement this in powershell.

**Comment by Nonary** [comment]
This is probably caused by my default 3840x2400 override. I am going to change it to 2560x1600 since this resolution is available on most peoples computers without needing something like CRU.

**Comment by jeff-os** [comment]
Have you considered re-implementing this in python? In Windows had to remove execution/script restrictions at a system level to even get all the powershell scripts to run and I don't like the idea of placing jobs in my task scheduler nor keeping those restrictions off.  Python would also be easier to make it multiplatform in OSX/Linux/etc.

I used ideas from your powershells scripts and slapped something together in python and it's more or less suited to my own personal use case (Steam Deck.)

When the python scripts sees an event with "1280x800" (Deck Resolution) in the logs and if that event occured within the last 15 sec, it uses the win32api to set the desktop resolution to a 16:10 resolution defined by user.  By default the API won't try to change a resolution that it's already set to, so it doesn't matter if there are many "1280x800" messages in that 15 second span.

What I'm struggling with is setting the resolution back to 4K.  How are you able to tell when a particular host has disconnected? The only thing I have to go by is the 'Info: CLIENT DISCONNECTED' message.  Which works as long as the monitor is on, but if the monitor goes to sleep and it's turned back on it doesn't catch that "Client Disconnect" message because it happened to long ago.

I suppose I could look for the very last "CLIENT DISCONNECT" string in the log, and then add a condition to revert the Desktop resolution to 4K if there are no "1280x800"  proceeding it. I looked through your powershell scripts and couldn't find an obvious way that you're using to determine when the client disconnects.

**Comment by Nonary** [comment]
> Have you considered re-implementing this in python? In Windows had to remove execution/script restrictions at a system level to even get all the powershell scripts to run and I don't like the idea of placing jobs in my task scheduler nor keeping those restrictions off. Python would also be easier to make it multiplatform in OSX/Linux/etc.
> 
> I used ideas from your powershells scripts and slapped something together in python and it's more or less suited to my own personal use case (Steam Deck.)
> 
> When the python scripts sees an event with "1280x800" (Deck Resolution) in the logs and if that event occured within the last 15 sec, it uses the win32api to set the desktop resolution to a 16:10 resolution defined by user. By default the API won't try to change a resolution that it's already set to, so it doesn't matter if there are many "1280x800" messages in that 15 second span.
> 
> What I'm struggling with is setting the resolution back to 4K. How are you able to tell when a particular host has disconnected? The only thing I have to go by is the 'Info: CLIENT DISCONNECTED' message. Which works as long as the monitor is on, but if the monitor goes to sleep and it's turned back on it doesn't catch that "Client Disconnect" message because it happened to long ago.
> 
> I suppose I could look for the very last "CLIENT DISCONNECT" string in the log, and then add a condition to revert the Desktop resolution to 4K if there are no "1280x800" proceeding it. I looked through your powershell scripts and couldn't find an obvious way that you're using to determine when the client disconnects.

The precommand version of the script does not need to rely on setting a task or startup item. The other version of the script, which uses the task, is more for GFE users or those who prefer it to be a task or struggle with basic computer skills essentially.

As for figuring out when it disconnects, in the precommand version it uses a named pipe to send a termination signal to the script. For the other version, it monitors the UDP ports for the Sunshine process. This would be challenging to do in Python because there isn't a windows API exposed that allows you to see UDP ports in use if the process you are monitoring is running at SYSTEM level.

As for the client disconnect in log, that would work but like you've noticed, it has problems in edge cases. Which isn't a huge deal for the precommand version since it uses a named pipe. But I have it terminate after 120 seconds of inactivity, by design though.

**Comment by jeff-os** [comment]
> But I have it terminate after 120 seconds of inactivity, by design though.

I think that makes sense for what I'm trying to do.  Basically it'll switch to 16:10 if deck resolution detected, and back to 16:9 if it's not detected for a couple minutes.

Trying to make it fit general use cases is beyond my programming skills, but this solution is good enough for a personal script.  Thanks!

**Comment by Nonary** [comment]
> > But I have it terminate after 120 seconds of inactivity, by design though.
> 
> 
> 
> I think that makes sense for what I'm trying to do.  Basically it'll switch to 16:10 if deck resolution detected, and back to 16:9 if it's not detected for a couple minutes.
> 
> 
> 
> Trying to make it fit general use cases is beyond my programming skills, but this solution is good enough for a personal script.  Thanks!

Basically the main reason I chose powershell is because it is installed by default on windows. It also happens to contain a function that allows me to check to see if certain ports are being used (even if the process it is checking is at a higher elevation level)

When I looked around in mimicking the same behavior in python, it didn't have a solution that I could find that didn't require putting python at system level, or to simply launch powershell from within python which would defeat the purpose.
